import sbt._
import Keys._
import scala.util.Using
import scala.io.Source

/** Auto plugin to generate Definitions object containing enum constants from definitionsSchema.schema.json */
object DefinitionsGeneratorPlugin extends AutoPlugin {
  object autoImport {
    val generateDefinitionsConstants = taskKey[Seq[File]]("Generate Definitions enum constants")
    val definitionsSchemaJsonFile = settingKey[File]("Location of definitionsSchema.schema.json")
  }
  import autoImport._

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Setting[_]] = Seq(
    definitionsSchemaJsonFile := baseDirectory.value / "metadata-schema" / "definitionsSchema.schema.json",
    Compile / sourceGenerators += generateDefinitionsConstants.taskValue,
    generateDefinitionsConstants := {
      val log = streams.value.log
      val schemaFile = definitionsSchemaJsonFile.value
      if (!schemaFile.exists()) {
        log.warn(s"Schema file not found: $schemaFile")
        Seq.empty[File]
      } else {
        import ujson.*
        val jsonStr = Using(Source.fromFile(schemaFile)(scala.io.Codec.UTF8))(_.mkString).get
        val parsed = ujson.read(jsonStr)
        val definitions: Seq[(String, Seq[String])] = parsed.obj.get("definitions") match {
          case Some(defs: ujson.Obj) =>
            defs.value.map { case (name, defObj) =>
              val values = defObj.obj.get("enum") match {
                case Some(arr: ujson.Arr) => arr.value.map(_.str).toSeq
                case _ => Seq.empty
              }
              (name, values)
            }.toSeq.sortBy(_._1)
          case _ => Seq.empty
        }

        def sanitizeIdentifier(str: String): String = {
          var result = str.replaceAll("[^A-Za-z0-9_]", "_")
          // Ensure it doesn't start with a number
          if (result.nonEmpty && result.head.isDigit) {
            result = "_" + result
          }
          result
        }

        val objectsBuilder = new StringBuilder
        definitions.foreach { case (defName, enumValues) =>
          val safeName = sanitizeIdentifier(defName)
          objectsBuilder.append("  object ").append(safeName).append(" {\n")

          // Generate a list of all values only (no individual val declarations)
          objectsBuilder.append("    def all: Seq[String] = Seq(\n")
          enumValues.zipWithIndex.foreach { case (value, idx) =>
            val escapedValue = value.replace("\\", "\\\\").replace("\"", "\\\"")
            objectsBuilder.append("      \"").append(escapedValue).append("\"")
            if (idx < enumValues.size - 1) {
              objectsBuilder.append(",")
            }
            objectsBuilder.append("\n")
          }
          objectsBuilder.append("    )\n")

          objectsBuilder.append("  }\n")
        }

        // Build final code
        val code =
          "package uk.gov.nationalarchives.tdr.schema.generated\n" +
          "// AUTO-GENERATED: DO NOT EDIT. Generated by DefinitionsGeneratorPlugin.\n" +
          "object Definitions {\n" +
          objectsBuilder.toString +
          "}\n"
        val outDir = (Compile / sourceManaged).value / "generated"
        outDir.mkdirs()
        val outFile = outDir / "Definitions.scala"
        IO.write(outFile, code)
        log.info(s"Generated ${outFile.getAbsolutePath} with ${definitions.size} enum definitions.")
        Seq(outFile)
      }
    }
  )
}

