import sbt._
import Keys._
import scala.util.Using
import scala.io.Source

/** Auto plugin to generate DisallowedPuids object containing all disallowed PUIDs from disallowed-puids.json */
object DisallowedPuidsGeneratorPlugin extends AutoPlugin {
  object autoImport {
    val generateDisallowedPuidsConstants = taskKey[Seq[File]]("Generate DisallowedPuids list")
    val disallowedPuidsJsonFile = settingKey[File]("Location of disallowed-puids.json")
  }
  import autoImport._

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Setting[_]] = Seq(
    disallowedPuidsJsonFile := baseDirectory.value / "puids" / "disallowed-puids.json",
    Compile / sourceGenerators += generateDisallowedPuidsConstants.taskValue,
    generateDisallowedPuidsConstants := {
      val log = streams.value.log
      val jsonFile = disallowedPuidsJsonFile.value
      if (!jsonFile.exists()) {
        log.warn(s"JSON file not found: $jsonFile")
        Seq.empty[File]
      } else {
        val jsonStr = Using(Source.fromFile(jsonFile)(scala.io.Codec.UTF8))(_.mkString).get
        val parsed = ujson.read(jsonStr)

        // Extract all PUID objects from the array
        case class PuidEntry(puid: String, active: Boolean, reason: String, puidDescription: String)

        val puidEntries: Seq[PuidEntry] = parsed.arr.map { item =>
          val puid = item.obj.get("puid").map(_.str).getOrElse("")
          val active = item.obj.get("active") match {
            case Some(ujson.Bool(value)) => value
            case _ => false
          }
          val reason = item.obj.get("reason").map(_.str).getOrElse("")
          val puidDescription = item.obj.get("puidDescription").map(_.str).getOrElse("")
          PuidEntry(puid, active, reason, puidDescription)
        }.toSeq

        // Generate Scala code with case class and list
        val code =
          "package uk.gov.nationalarchives.tdr.schema.generated\n" +
          "// AUTO-GENERATED: DO NOT EDIT. Generated by DisallowedPuidsGeneratorPlugin.\n" +
          "object DisallowedPuids {\n" +
          "  case class PuidEntry(puid: String, active: Boolean, reason: String, puidDescription: String)\n" +
          "\n" +
          "  def all: Seq[PuidEntry] = Seq(\n" +
          puidEntries.zipWithIndex.map { case (entry, idx) =>
            val escapedPuid = entry.puid.replace("\\", "\\\\").replace("\"", "\\\"")
            val escapedReason = entry.reason.replace("\\", "\\\\").replace("\"", "\\\"")
            val escapedDesc = entry.puidDescription.replace("\\", "\\\\").replace("\"", "\\\"")
            "    PuidEntry(\"" + escapedPuid + "\", " + entry.active + ", \"" + escapedReason + "\", \"" + escapedDesc + "\")" +
            (if (idx < puidEntries.size - 1) "," else "")
          }.mkString("\n") +
          "\n  )\n" +
          "}\n"

        val outDir = (Compile / sourceManaged).value / "generated"
        outDir.mkdirs()
        val outFile = outDir / "DisallowedPuids.scala"
        IO.write(outFile, code)
        log.info(s"Generated ${outFile.getAbsolutePath} with ${puidEntries.size} PUID entries.")
        Seq(outFile)
      }
    }
  )
}



