import sbt._
import Keys._
import scala.util.Using
import scala.io.Source

/** Auto plugin to generate ExcludedFilenames object from excluded-filenames.json */
object ExcludedFilenamesGeneratorPlugin extends AutoPlugin {
  object autoImport {
    val generateExcludedFilenamesConstants = taskKey[Seq[File]]("Generate ExcludedFilenames list")
    val excludedFilenamesJsonFile = settingKey[File]("Location of excluded-filenames.json")
  }
  import autoImport._

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Setting[_]] = Seq(
    excludedFilenamesJsonFile := baseDirectory.value / "puids" / "excluded-filenames.json",
    Compile / sourceGenerators += generateExcludedFilenamesConstants.taskValue,
    generateExcludedFilenamesConstants := {
      val log = streams.value.log
      val jsonFile = excludedFilenamesJsonFile.value
      if (!jsonFile.exists()) {
        log.warn(s"JSON file not found: $jsonFile")
        Seq.empty[File]
      } else {
        val jsonStr = Using(Source.fromFile(jsonFile)(scala.io.Codec.UTF8))(_.mkString).get
        val parsed = ujson.read(jsonStr)

        case class FilenamePattern(pattern: String, patternType: String, caseInsensitive: Boolean, description: String)

        val patterns: Seq[FilenamePattern] = parsed.arr.map { item =>
          val pattern = item.obj.get("pattern").map(_.str).getOrElse("")
          val patternType = item.obj.get("type").map(_.str).getOrElse("exact")
          val caseInsensitive = item.obj.get("caseInsensitive") match {
            case Some(ujson.Bool(value)) => value
            case _ => false
          }
          val description = item.obj.get("description").map(_.str).getOrElse("")
          FilenamePattern(pattern, patternType, caseInsensitive, description)
        }

        val code =
          """package uk.gov.nationalarchives.tdr.schema.generated
// AUTO-GENERATED: DO NOT EDIT. Generated by ExcludedFilenamesGeneratorPlugin.
import scala.util.matching.Regex

object ExcludedFilenames {
  case class FilenamePattern(
    pattern: String,
    patternType: String,
    caseInsensitive: Boolean,
    description: String
  ) {
    private lazy val regex: Regex = {
      val flags = if (caseInsensitive) "(?i)" else ""
      (flags + pattern).r
    }

    def matches(filename: String): Boolean = {
      patternType match {
        case "exact" =>
          if (caseInsensitive) filename.equalsIgnoreCase(pattern)
          else filename == pattern
        case "regex" =>
          regex.findFirstIn(filename).isDefined
        case _ => false
      }
    }
  }

  val all: Seq[FilenamePattern] = Seq(
""" +
          patterns.zipWithIndex.map { case (p, idx) =>
            val escapedPattern = p.pattern.replace("\\", "\\\\").replace("\"", "\\\"")
            val escapedDesc = p.description.replace("\\", "\\\\").replace("\"", "\\\"")
            "    FilenamePattern(\"" + escapedPattern + "\", \"" + p.patternType + "\", " +
            p.caseInsensitive + ", \"" + escapedDesc + "\")" +
            (if (idx < patterns.size - 1) "," else "")
          }.mkString("\n") +
          """
  )

  def isExcluded(filename: String): Boolean = all.exists(_.matches(filename))
}
"""

        val outDir = (Compile / sourceManaged).value / "generated"
        outDir.mkdirs()
        val outFile = outDir / "ExcludedFilenames.scala"
        IO.write(outFile, code)
        log.info(s"Generated ${outFile.getAbsolutePath} with ${patterns.size} filename pattern entries.")
        Seq(outFile)
      }
    }
  )
}
