import sbt._
import Keys._
import scala.io.Source
import scala.util.Using

/** Auto plugin to generate HeaderSource values from config.json alternateKeys fields */
object HeaderSourceGeneratorPlugin extends AutoPlugin {
  object autoImport {
    val generateHeaderSources = taskKey[Seq[File]]("Generate HeaderSource values from config.json alternateKeys")
    val configJsonFile = settingKey[File]("Location of config.json")
  }
  import autoImport._

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Setting[_]] = Seq(
    configJsonFile := baseDirectory.value / "config-schema" / "config.json",
    Compile / sourceGenerators += generateHeaderSources.taskValue,
    generateHeaderSources := {
      val log = streams.value.log
      val inputFile = configJsonFile.value
      if (!inputFile.exists()) {
        log.warn(s"Config file not found: $inputFile")
        Seq.empty[File]
      } else {
        def toCaseObjectName(jsonFieldName: String): String = {
          val withWordBoundaries = jsonFieldName
            .replaceAll("([a-z0-9])([A-Z])", "$1 $2")
            .replaceAll("[^A-Za-z0-9]+", " ")
            .trim

          val capitalized = withWordBoundaries
            .split("\\s+")
            .filter(_.nonEmpty)
            .map(segment => segment.head.toUpper + segment.tail)
            .mkString

          if (capitalized.nonEmpty && capitalized.head.isDigit) s"_$capitalized" else capitalized
        }

        val jsonStr = Using(Source.fromFile(inputFile)(scala.io.Codec.UTF8))(_.mkString).get
        val parsed = ujson.read(jsonStr)
        val headerFields = parsed.obj.get("configItems") match {
          case Some(items: ujson.Arr) =>
            items.value
              .flatMap(_.obj.get("alternateKeys").collect { case arr: ujson.Arr => arr.value }.getOrElse(Seq.empty))
              .flatMap(_.obj.keys)
              .distinct
              .sorted
          case _ => Seq.empty[String]
        }

        val collisions = headerFields.groupBy(toCaseObjectName).collect { case (generatedName, originalFields) if originalFields.distinct.size > 1 =>
          generatedName -> originalFields.sorted
        }
        require(collisions.isEmpty, s"HeaderSource generation produced duplicate Scala identifiers: $collisions")

        val caseObjects = headerFields.map { fieldName =>
          val generatedName = toCaseObjectName(fieldName)
          s"""  case object $generatedName extends HeaderSource { val jsonFieldName = "$fieldName" }"""
        }

        val values = headerFields.map(fieldName => s"    ${toCaseObjectName(fieldName)}").mkString(",\n")

        val code =
          s"""package uk.gov.nationalarchives.tdr.schemautils
             |// AUTO-GENERATED: DO NOT EDIT. Generated by HeaderSourceGeneratorPlugin.
             |sealed trait HeaderSource {
             |  def jsonFieldName: String
             |}
             |
             |object HeaderSource {
             |${caseObjects.mkString("\n")}
             |
             |  val values: List[HeaderSource] = List(
             |$values
             |  )
             |}
             |""".stripMargin

        val outDir = (Compile / sourceManaged).value / "generated"
        outDir.mkdirs()
        val outFile = outDir / "HeaderSource.scala"
        IO.write(outFile, code)
        log.info(s"Generated ${outFile.getAbsolutePath} with ${headerFields.size} header sources.")
        Seq(outFile)
      }
    }
  )
}

