import sbt._
import Keys._
import scala.util.Using
import scala.io.Source

/** Auto plugin to generate MetadataTemplate object containing metadata properties from metadata-template.json */
object MetadataTemplateGeneratorPlugin extends AutoPlugin {
  object autoImport {
    val generateMetadataTemplateConstants = taskKey[Seq[File]]("Generate MetadataTemplate properties")
    val metadataTemplateJsonFile = settingKey[File]("Location of metadata-template.json")
  }
  import autoImport._

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Setting[_]] = Seq(
    metadataTemplateJsonFile := baseDirectory.value / "guidance" / "metadata-template.json",
    Compile / sourceGenerators += generateMetadataTemplateConstants.taskValue,
    generateMetadataTemplateConstants := {
      val log = streams.value.log
      val jsonFile = metadataTemplateJsonFile.value
      if (!jsonFile.exists()) {
        log.warn(s"JSON file not found: $jsonFile")
        Seq.empty[File]
      } else {
        import ujson.*
        val jsonStr = Using(Source.fromFile(jsonFile)(scala.io.Codec.UTF8))(_.mkString).get
        val parsed = ujson.read(jsonStr)

        // Extract metadata template objects
        case class MetadataProperty(
          property: String,
          details: String,
          format: String,
          tdrRequirement: String,
          example: String
        )

        val metadataProperties: Seq[MetadataProperty] = parsed.arr.map { item =>
          val property = item.obj.get("property").map(_.str).getOrElse("")
          val details = item.obj.get("details").map(_.str).getOrElse("")
          val format = item.obj.get("format").map(_.str).getOrElse("")
          val tdrRequirement = item.obj.get("tdrRequirement").map(_.str).getOrElse("")
          val example = item.obj.get("example").map(_.str).getOrElse("")
          MetadataProperty(property, details, format, tdrRequirement, example)
        }.toSeq

        // Generate Scala code with case class and list
        val code =
          "package uk.gov.nationalarchives.tdr.schema.generated\n" +
          "// AUTO-GENERATED: DO NOT EDIT. Generated by MetadataTemplateGeneratorPlugin.\n" +
          "object MetadataTemplate {\n" +
          "  case class MetadataProperty(\n" +
          "    property: String,\n" +
          "    details: String,\n" +
          "    format: String,\n" +
          "    tdrRequirement: String,\n" +
          "    example: String\n" +
          "  )\n" +
          "\n" +
          "  def all: Seq[MetadataProperty] = Seq(\n" +
          metadataProperties.zipWithIndex.map { case (prop, idx) =>
            val escapedProperty = prop.property.replace("\\", "\\\\").replace("\"", "\\\"")
            val escapedDetails = prop.details.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
            val escapedFormat = prop.format.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
            val escapedRequirement = prop.tdrRequirement.replace("\\", "\\\\").replace("\"", "\\\"")
            val escapedExample = prop.example.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
            "    MetadataProperty(\"" + escapedProperty + "\", \"" + escapedDetails + "\", \"" + escapedFormat + "\", \"" + escapedRequirement + "\", \"" + escapedExample + "\")" +
            (if (idx < metadataProperties.size - 1) "," else "")
          }.mkString("\n") +
          "\n  )\n" +
          "}\n"

        val outDir = (Compile / sourceManaged).value / "generated"
        outDir.mkdirs()
        val outFile = outDir / "MetadataTemplate.scala"
        IO.write(outFile, code)
        log.info(s"Generated ${outFile.getAbsolutePath} with ${metadataProperties.size} metadata properties.")
        Seq(outFile)
      }
    }
  )
}

